-- MySQL Script generated by MySQL Workbench
-- 07/07/16 17:49:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hydb` ;

-- -----------------------------------------------------
-- Schema hydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hydb` DEFAULT CHARACTER SET utf8 ;
USE `hydb` ;

-- -----------------------------------------------------
-- Table `hydb`.`t_position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hydb`.`t_position` ;

CREATE TABLE IF NOT EXISTS `hydb`.`t_position` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '职位名称',
  `address` VARCHAR(45) NOT NULL COMMENT '工作地址',
  `duty` TEXT NOT NULL COMMENT '职责',
  `recruitment` TEXT NOT NULL COMMENT '招聘条件',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
